CI: Expose detected plugin name to other workflow jobs
obsproject/obs-plugintemplate pull request #109
Opened 2023-12-11 17:36 UTC by PatTheMav

### Description
Adds early detection of the configured plugin name in workflows so the name can be re-used in later workflows without the need to do a full repository checkout or installation of 3rd party utilities (e.g. the release creation step).

### Motivation and Context
Reduce necessary fixup steps for plugin developers when finalising their releases.

Fixes https://github.com/obsproject/obs-plugintemplate/issues/105.

### How Has This Been Tested?
Tested with a tagged release on a fork of the repository.

### Types of changes
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-12-12 23:51 UTC, RytoEX requested changes

2023-12-12 23:51 UTC, RytoEX commented on .github/workflows/build-project.yaml
> +        value: ${{ jobs.check-event.outputs.pluginName}}
```suggestion
        value: ${{ jobs.check-event.outputs.pluginName }}
```

2023-12-16 23:46 UTC, RytoEX approved these changes
Seems fine.

2023-12-19 04:12 UTC, CodeYan01 commented
With the new `displayName` change, have you tested creating a new release, with a space in the displayName? I am getting an error: https://github.com/CodeYan01/media-playlist-source/actions/runs/7257209427/job/19770748632

2023-12-19 21:23 UTC, PatTheMav commented
> With the new `displayName` change, have you tested creating a new release, with a space in the displayName? I am getting an error: https://github.com/CodeYan01/media-playlist-source/actions/runs/7257209427/job/19770748632

Right, it's not supposed to be used for file names now that it can have spaces and other weird characters in it, forgot to remove that again.

2023-12-20 16:47 UTC, PatTheMav commented
@CodeYan01 pls check again.

2023-12-21 15:17 UTC, CodeYan01 commented
In the Issue, you commented that it will fallback to `name` if `displayName` is not available, but I'm getting an error when the field is not there. https://github.com/CodeYan01/media-playlist-source/actions/runs/7284773565

With the `displayName` it now works perfectly. https://github.com/CodeYan01/media-playlist-source/actions/runs/7284781779

Thank you!

2023-12-21 15:56 UTC, PatTheMav commented
> In the Issue, you commented that it will fallback to `name` if `displayName` is not available, but I'm getting an error when the field is not there. https://github.com/CodeYan01/media-playlist-source/actions/runs/7284773565
> 
> With the `displayName` it now works perfectly. https://github.com/CodeYan01/media-playlist-source/actions/runs/7284781779
> 
> Thank you!

Ah, good old `pipefail`, should be fixed in a bit.

2023-12-21 16:21 UTC, CodeYan01 commented
Tested both cases, works now.

2023-12-21 16:50 UTC, merged